services:
  - type: web
    name: chat-application
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT chat_project.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chat-redis
          type: redis
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
    autoDeploy: true
